### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by Johnadibe** [Johnadibe/recipe-app#7]
There are 2 members of our team. @Johnadibe has been assigned to Team Member 1 task, and @jodavid444 to Team Member 2. 
Here is the [Link](https://github.com/users/Johnadibe/projects/3) to the project.

**Comment by OLIPLICHE** [comment]
@Johnadibe Make your GitHub available. Kindly meet me on slack, don't comment here.
![Capture](https://github.com/Johnadibe/recipe-app/assets/63972670/6f504ae2-9a4e-42cc-9a48-d0e600643cd9)

**Comment by Johnadibe** [comment]
Hello @OLIPLICHE, I have made the necessary changes. I added the `Write unit and integration tests` inside the General shopping list view card. Based on what you suggested to follow the design of the card as the Original gives it, GitHub changed their UI on the Projects Board Task. Thank you

**Comment by Johnadibe** [comment]
Hello @Munsa1, I have fixed all requested changes.👍

**Comment by rotimiazeez** [comment]
Hi Team 👏🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
